### ISSUE TITLE
Open source projects led and managed by Latvians, made by international teams

### ISSUE THREAD

**Issue by manpages** [ummahusla/Made-in-Latvia#2]
Are open source projects led and managed by Latvians, made by international teams subject for inclusion in this repository?
One such project is a project led by me — https://github.com/serokell/rscoin, which I think is cool and could be included in your list. :)

**Comment by ummahusla** [comment]
Well, it's kinda tricky one! On the one hand side technically it's not built in Latvia, but on the other hand, if you lead this project, I more than happy to add it :)
