### ISSUE TITLE
Remove HTML and CSS

### ISSUE THREAD

**Issue by manpages** [ummahusla/Made-in-Latvia#4]
It doesn't really make sense to have markup languages and styling languages here.
Yes, there are projects like Twitter Bootstrap, but how would you classify it? Javascript (they use some meta-programming to generate CSS)? HTML? CSS? Those classifications don't really _classify_ anything because you can't do anything generic with HTML and anything stand-alone (meaningful) in CSS.

**Comment by ummahusla** [comment]
I can agree that we can remove HTML, but I personally would leave CSS, because there are a lot of developers who are working on CSS frameworks.
